### ISSUE TITLE
Refactor automatic docs deployment

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/winchecksec#1053]
The current `docs-deploy.yml` should be rewritten to use GitHub's first-party support for publishing in GitHub Actions, like so:

```yaml
name: Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # DOCS STEP HERE

      - name: upload docs artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./html/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      # NOTE: Needed to push to the repository.
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
```
